# Generated by Django 2.2 on 2019-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answers_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='img_url',
            field=models.TextField(blank=True),
        ),
    ]
