# Generated by Django 2.2 on 2019-05-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answers_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Answers')),
            ],
        ),
    ]
